<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link } from '@inertiajs/vue3';
import { create, show } from '@/actions/App/Http/Controllers/ReportController';

interface ReportRow {
    id: number;
    municipality: string;
    range_start: string;
    range_end: string;
    generated_by: { id: number; name: string } | null;
}

defineProps<{
    reports: {
        data: (ReportRow & { generated_by: { name: string } | null })[];
        links: { url: string | null; label: string; active: boolean }[];
    };
}>();
</script>

<template>
    <Head title="Reports" />

    <AuthenticatedLayout>
        <template #header>
            <div class="flex items-center justify-between">
                <h2 class="text-xl leading-tight font-semibold text-gray-800">
                    Reports
                </h2>
                <Link
                    :href="create().url"
                    class="rounded-md bg-gray-800 px-4 py-2 text-sm font-medium text-white hover:bg-gray-700"
                >
                    New Report
                </Link>
            </div>
        </template>

        <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
            <div class="overflow-hidden rounded-lg bg-white shadow">
                <table class="min-w-full divide-y divide-gray-200 text-sm">
                    <thead class="bg-gray-50 text-left text-gray-600">
                        <tr>
                            <th class="px-4 py-3">Municipality</th>
                            <th class="px-4 py-3">Range</th>
                            <th class="px-4 py-3">Generated by</th>
                            <th class="px-4 py-3"></th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        <tr v-for="report in reports.data" :key="report.id">
                            <td class="px-4 py-3">{{ report.municipality }}</td>
                            <td class="px-4 py-3">
                                {{ report.range_start.slice(0, 10) }} to
                                {{ report.range_end.slice(0, 10) }}
                            </td>
                            <td class="px-4 py-3">
                                {{ report.generated_by?.name }}
                            </td>
                            <td class="px-4 py-3 text-right">
                                <Link
                                    :href="show(report.id).url"
                                    class="text-indigo-600 hover:underline"
                                >
                                    View
                                </Link>
                            </td>
                        </tr>
                        <tr v-if="!reports.data.length">
                            <td
                                colspan="4"
                                class="px-4 py-6 text-center text-gray-500"
                            >
                                No reports yet.
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="mt-4 flex flex-wrap gap-1">
                <template v-for="link in reports.links" :key="link.label">
                    <Link
                        v-if="link.url"
                        :href="link.url"
                        class="rounded border px-3 py-1 text-sm"
                        :class="
                            link.active
                                ? 'bg-gray-800 text-white'
                                : 'bg-white text-gray-700'
                        "
                        v-html="link.label"
                    />
                    <span
                        v-else
                        class="px-3 py-1 text-sm text-gray-400"
                        v-html="link.label"
                    />
                </template>
            </div>
        </div>
    </AuthenticatedLayout>
</template>
