<script setup lang="ts">
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { Head, Link } from '@inertiajs/vue3';
import { index } from '@/actions/App/Http/Controllers/ReportController';

defineProps<{
    report: {
        id: number;
        municipality: string;
        range_start: string;
        range_end: string;
        created_at: string;
        generated_by: { name: string } | null;
        summary_data: {
            total_scans: number;
            confirmed_cases: number;
            per_disease: { disease: string; count: number }[];
            top_disease: string | null;
        };
    };
}>();
</script>

<template>
    <Head title="Report" />

    <AuthenticatedLayout>
        <template #header>
            <div class="flex items-center justify-between">
                <h2 class="text-xl leading-tight font-semibold text-gray-800">
                    {{ report.municipality }} Report
                </h2>
                <Link
                    :href="index().url"
                    class="text-sm text-indigo-600 hover:underline"
                    >Back to reports</Link
                >
            </div>
        </template>

        <div class="mx-auto max-w-4xl space-y-6 py-6 sm:px-6 lg:px-8">
            <p class="text-sm text-gray-600">
                {{ report.range_start.slice(0, 10) }} to
                {{ report.range_end.slice(0, 10) }}, generated by
                {{ report.generated_by?.name }}
            </p>

            <div class="grid grid-cols-3 gap-4">
                <div class="rounded-lg bg-white p-4 shadow">
                    <p class="text-sm text-gray-500">Total scans</p>
                    <p class="text-2xl font-semibold">
                        {{ report.summary_data.total_scans }}
                    </p>
                </div>
                <div class="rounded-lg bg-white p-4 shadow">
                    <p class="text-sm text-gray-500">Confirmed cases</p>
                    <p class="text-2xl font-semibold">
                        {{ report.summary_data.confirmed_cases }}
                    </p>
                </div>
                <div class="rounded-lg bg-white p-4 shadow">
                    <p class="text-sm text-gray-500">Top disease</p>
                    <p class="text-2xl font-semibold">
                        {{ report.summary_data.top_disease ?? 'None' }}
                    </p>
                </div>
            </div>

            <div class="overflow-hidden rounded-lg bg-white shadow">
                <table class="min-w-full divide-y divide-gray-200 text-sm">
                    <thead class="bg-gray-50 text-left text-gray-600">
                        <tr>
                            <th class="px-4 py-3">Disease</th>
                            <th class="px-4 py-3">Cases</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        <tr
                            v-for="row in report.summary_data.per_disease"
                            :key="row.disease"
                        >
                            <td class="px-4 py-3">{{ row.disease }}</td>
                            <td class="px-4 py-3">{{ row.count }}</td>
                        </tr>
                        <tr v-if="!report.summary_data.per_disease.length">
                            <td
                                colspan="2"
                                class="px-4 py-6 text-center text-gray-500"
                            >
                                No cases in this range.
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </AuthenticatedLayout>
</template>
